#!/bin/bash
set -e

cd /opt/start-burger
git pull
source venv/bin/activate

pip install -r requirements.txt
npm install
npm ci --dev

python manage.py migrate
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
python manage.py collectstatic --noinput

systemctl restart burger
