#!/bin/bash
set -e

cd /opt/start-burger
git pull
source venv/bin/activate
source .env

pip install -r requirements.txt
npm install
npm ci --dev

python manage.py migrate
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
python manage.py collectstatic --noinput

systemctl restart burger
git_rev=$(git rev-parse --short HEAD)

curl -H "X-Rollbar-Access-Token: $ROLLBAR_ACCESS_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{"environment": "production", "revision": "'$git_rev'", "rollbar_name": "tony", "local_username": "root", "comment": "BASH deployment", "status": "succeeded"}'
