version: '3.8'

volumes:
  db_data:
  static_volume:
  media_volume:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python3 /usr/src/app/manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8008:8000"
    env_file:
      - ./.env
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./db/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ./node_modules/.bin/parcel watch ./bundles-src/index.js --dist-dir bundles --public-url "./"
    volumes:
      - static_volume:/opt/frontend/staticfiles
    ports:
      - "8003:80"
