version: '3.8'

volumes:
  db_data:
  static_volume:
  media_volume:
  bundles:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python3 /usr/src/app/manage.py migrate --noinput && python3 /usr/src/app/manage.py collectstatic --noinput && gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application"
    restart: always
    ports:
      - "8008:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend/staticfiles:/usr/src/app/staticfiles
      - ./backend/media:/usr/src/app/media
      - ./bundles:/usr/src/app/bundles
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
