# Generated by Django 3.2 on 2022-04-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_rename_items_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='qty',
            new_name='quantity',
        ),
    ]
