# Generated by Django 3.2 on 2022-04-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Необработанный'), (2, 'Подтверждённый')], db_index=True, default=1, verbose_name='статус'),
        ),
    ]
