# Generated by Django 3.2 on 2022-04-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20220421_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(1, 'Наличностью'), (2, 'Электронно')], db_index=True, default=2, verbose_name='метод оплаты'),
        ),
    ]
