# Generated by Django 3.2 on 2022-04-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_rename_phone_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
    ]
