# Generated by Django 3.2 on 2022-04-17 01:21

from django.db import migrations
from itertools import chain


def copy_price_to_orders(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    order_products = OrderProduct.objects.all()
    order_iterator = order_products.iterator()
    for order_product in chain(order_iterator):
        order_product.price = order_product.product.price
        order_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_orders)
    ]
