# Generated by Django 3.2 on 2022-04-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220417_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'новый'), (2, 'подтверждён')], db_index=True, default=1, verbose_name='статус'),
        ),
    ]
